#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Pp0012

#include "Basic.hpp"

#include "ABP_Pp0012_classes.hpp"
#include "ABP_Pp0012_parameters.hpp"


namespace SDK
{

// Function ABP_Pp0012.ABP_Pp0012_C.ExecuteUbergraph_ABP_Pp0012
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Pp0012_C::ExecuteUbergraph_ABP_Pp0012(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Pp0012_C", "ExecuteUbergraph_ABP_Pp0012");

	Params::ABP_Pp0012_C_ExecuteUbergraph_ABP_Pp0012 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Pp0012.ABP_Pp0012_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_Pp0012_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Pp0012_C", "AnimGraph");

	Params::ABP_Pp0012_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

