#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALS_Animation_BPI

#include "Basic.hpp"

#include "ALS_Animation_BPI_classes.hpp"
#include "ALS_Animation_BPI_parameters.hpp"


namespace SDK
{

// Function ALS_Animation_BPI.ALS_Animation_BPI_C.BPI_Jumped
// (Public, BlueprintCallable, BlueprintEvent)

void IALS_Animation_BPI_C::BPI_Jumped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ALS_Animation_BPI_C", "BPI_Jumped");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ALS_Animation_BPI.ALS_Animation_BPI_C.BPI_SetGroundedEntryState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EGroundedEntryState                     GroundedEntryState                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IALS_Animation_BPI_C::BPI_SetGroundedEntryState(EGroundedEntryState GroundedEntryState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ALS_Animation_BPI_C", "BPI_SetGroundedEntryState");

	Params::ALS_Animation_BPI_C_BPI_SetGroundedEntryState Parms{};

	Parms.GroundedEntryState = GroundedEntryState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ALS_Animation_BPI.ALS_Animation_BPI_C.BPI_SetOverlayOverrideState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   OverlayOverrideState                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IALS_Animation_BPI_C::BPI_SetOverlayOverrideState(int32 OverlayOverrideState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ALS_Animation_BPI_C", "BPI_SetOverlayOverrideState");

	Params::ALS_Animation_BPI_C_BPI_SetOverlayOverrideState Parms{};

	Parms.OverlayOverrideState = OverlayOverrideState;

	UObject::ProcessEvent(Func, &Parms);
}

}

