#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlPhaseDead

#include "Basic.hpp"

#include "BP_BtlPhaseDead_classes.hpp"
#include "BP_BtlPhaseDead_parameters.hpp"


namespace SDK
{

// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.ExecuteUbergraph_BP_BtlPhaseDead
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlPhaseDead_C::ExecuteUbergraph_BP_BtlPhaseDead(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "ExecuteUbergraph_BP_BtlPhaseDead");

	Params::BP_BtlPhaseDead_C_ExecuteUbergraph_BP_BtlPhaseDead Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.Has Finished LS ahead of Retry Selection
// (BlueprintCallable, BlueprintEvent)

void ABP_BtlPhaseDead_C::Has_Finished_LS_ahead_of_Retry_Selection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "Has Finished LS ahead of Retry Selection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.Has Finished Retry Selection
// (BlueprintCallable, BlueprintEvent)

void ABP_BtlPhaseDead_C::Has_Finished_Retry_Selection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "Has Finished Retry Selection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.Has Finished Retry LS
// (BlueprintCallable, BlueprintEvent)

void ABP_BtlPhaseDead_C::Has_Finished_Retry_LS()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "Has Finished Retry LS");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.On Play Sequence
// (BlueprintCallable, BlueprintEvent)

void ABP_BtlPhaseDead_C::On_Play_Sequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "On Play Sequence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_BtlPhaseDead_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.Has Finished Finale Camera
// (BlueprintCallable, BlueprintEvent)

void ABP_BtlPhaseDead_C::Has_Finished_Finale_Camera()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "Has Finished Finale Camera");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlPhaseDead_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "ReceiveTick");

	Params::BP_BtlPhaseDead_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_BtlPhaseDead_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.OnLoaded_5A6DB0FE4E63032DCE533BA4AC55607D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlPhaseDead_C::OnLoaded_5A6DB0FE4E63032DCE533BA4AC55607D(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "OnLoaded_5A6DB0FE4E63032DCE533BA4AC55607D");

	Params::BP_BtlPhaseDead_C_OnLoaded_5A6DB0FE4E63032DCE533BA4AC55607D Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.OnLoaded_F299919840F6E357EA79F088AFEB262D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlPhaseDead_C::OnLoaded_F299919840F6E357EA79F088AFEB262D(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "OnLoaded_F299919840F6E357EA79F088AFEB262D");

	Params::BP_BtlPhaseDead_C_OnLoaded_F299919840F6E357EA79F088AFEB262D Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.OnLoaded_AF8919F940C1409C2B2923937150EE2F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlPhaseDead_C::OnLoaded_AF8919F940C1409C2B2923937150EE2F(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "OnLoaded_AF8919F940C1409C2B2923937150EE2F");

	Params::BP_BtlPhaseDead_C_OnLoaded_AF8919F940C1409C2B2923937150EE2F Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.OnLoaded_BFD3285142E23A9177B8069FB03A6A4A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlPhaseDead_C::OnLoaded_BFD3285142E23A9177B8069FB03A6A4A(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "OnLoaded_BFD3285142E23A9177B8069FB03A6A4A");

	Params::BP_BtlPhaseDead_C_OnLoaded_BFD3285142E23A9177B8069FB03A6A4A Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_BtlPhaseDead_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.GetNextPhaseInBP
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABtlPhase*                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class ABtlPhase* ABP_BtlPhaseDead_C::GetNextPhaseInBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "GetNextPhaseInBP");

	Params::BP_BtlPhaseDead_C_GetNextPhaseInBP Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.Setup
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_BtlCameraManagerComponent_C*  Btl_CameraManager                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlPhaseDead_C::Setup(class UBP_BtlCameraManagerComponent_C* Btl_CameraManager)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "Setup");

	Params::BP_BtlPhaseDead_C_Setup Parms{};

	Parms.Btl_CameraManager = Btl_CameraManager;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.InitEvent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsRetry_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BtlPhaseDead_C::InitEvent(bool IsRetry_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "InitEvent");

	Params::BP_BtlPhaseDead_C_InitEvent Parms{};

	Parms.IsRetry_0 = IsRetry_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.HideAllEnemies
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BtlPhaseDead_C::HideAllEnemies()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "HideAllEnemies");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.HideOtherCharacters
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BtlPhaseDead_C::HideOtherCharacters()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "HideOtherCharacters");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.AllocateHeroToInvoke
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_BtlPhaseDead_C::AllocateHeroToInvoke()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "AllocateHeroToInvoke");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.CoordinateFogCenter
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BtlPhaseDead_C::CoordinateFogCenter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "CoordinateFogCenter");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlPhaseDead.BP_BtlPhaseDead_C.CheckProgressNextPhaseInBP
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool ABP_BtlPhaseDead_C::CheckProgressNextPhaseInBP() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlPhaseDead_C", "CheckProgressNextPhaseInBP");

	Params::BP_BtlPhaseDead_C_CheckProgressNextPhaseInBP Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

