#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlEffectUtensil

#include "Basic.hpp"

#include "BP_BtlEffectUtensil_classes.hpp"
#include "BP_BtlEffectUtensil_parameters.hpp"


namespace SDK
{

// Function BP_BtlEffectUtensil.BP_BtlEffectUtensil_C.ExecuteUbergraph_BP_BtlEffectUtensil
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlEffectUtensil_C::ExecuteUbergraph_BP_BtlEffectUtensil(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlEffectUtensil_C", "ExecuteUbergraph_BP_BtlEffectUtensil");

	Params::BP_BtlEffectUtensil_C_ExecuteUbergraph_BP_BtlEffectUtensil Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlEffectUtensil.BP_BtlEffectUtensil_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_BtlEffectUtensil_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlEffectUtensil_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlEffectUtensil.BP_BtlEffectUtensil_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlEffectUtensil_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlEffectUtensil_C", "ReceiveTick");

	Params::BP_BtlEffectUtensil_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlEffectUtensil.BP_BtlEffectUtensil_C.SetEffect
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UNiagaraComponent*                Niagara                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UBtlCoreComponent*                BtlCore_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BtlEffectUtensil_C::SetEffect(class UNiagaraComponent* Niagara, class UBtlCoreComponent* BtlCore_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlEffectUtensil_C", "SetEffect");

	Params::BP_BtlEffectUtensil_C_SetEffect Parms{};

	Parms.Niagara = Niagara;
	Parms.BtlCore_0 = BtlCore_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

