#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CharaDirLight

#include "Basic.hpp"

#include "BP_CharaDirLight_classes.hpp"
#include "BP_CharaDirLight_parameters.hpp"


namespace SDK
{

// Function BP_CharaDirLight.BP_CharaDirLight_C.ExecuteUbergraph_BP_CharaDirLight
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CharaDirLight_C::ExecuteUbergraph_BP_CharaDirLight(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CharaDirLight_C", "ExecuteUbergraph_BP_CharaDirLight");

	Params::BP_CharaDirLight_C_ExecuteUbergraph_BP_CharaDirLight Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CharaDirLight.BP_CharaDirLight_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CharaDirLight_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CharaDirLight_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CharaDirLight.BP_CharaDirLight_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_CharaDirLight_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CharaDirLight_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CharaDirLight.BP_CharaDirLight_C.SetLightParameterToMPC
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_CharaDirLight_C::SetLightParameterToMPC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CharaDirLight_C", "SetLightParameterToMPC");

	UObject::ProcessEvent(Func, nullptr);
}

}

