#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CharaPointLight

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_CharaPointLight.BP_CharaPointLight_C.UserConstructionScript
// 0x0008 (0x0008 - 0x0000)
struct BP_CharaPointLight_C_UserConstructionScript final
{
public:
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CharaPointLight_C_UserConstructionScript) == 0x000004, "Wrong alignment on BP_CharaPointLight_C_UserConstructionScript");
static_assert(sizeof(BP_CharaPointLight_C_UserConstructionScript) == 0x000008, "Wrong size on BP_CharaPointLight_C_UserConstructionScript");
static_assert(offsetof(BP_CharaPointLight_C_UserConstructionScript, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000000, "Member 'BP_CharaPointLight_C_UserConstructionScript::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CharaPointLight_C_UserConstructionScript, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000004, "Member 'BP_CharaPointLight_C_UserConstructionScript::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");

}

