#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FldCameraAreaNear

#include "Basic.hpp"

#include "Xrd777_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FldCameraAreaNear.BP_FldCameraAreaNear_C
// 0x0000 (0x0240 - 0x0240)
class ABP_FldCameraAreaNear_C final : public AAppCharTransparencyArea
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FldCameraAreaNear_C">();
	}
	static class ABP_FldCameraAreaNear_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FldCameraAreaNear_C>();
	}
};
static_assert(alignof(ABP_FldCameraAreaNear_C) == 0x000008, "Wrong alignment on ABP_FldCameraAreaNear_C");
static_assert(sizeof(ABP_FldCameraAreaNear_C) == 0x000240, "Wrong size on ABP_FldCameraAreaNear_C");

}

