#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_BtlGuiContactor

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_BtlGuiContactor.BPI_BtlGuiContactor_C
// 0x0000 (0x0028 - 0x0028)
class IBPI_BtlGuiContactor_C final : public IInterface
{
public:
	void FinishAlloutActor();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_BtlGuiContactor_C">();
	}
	static class IBPI_BtlGuiContactor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_BtlGuiContactor_C>();
	}
};
static_assert(alignof(IBPI_BtlGuiContactor_C) == 0x000008, "Wrong alignment on IBPI_BtlGuiContactor_C");
static_assert(sizeof(IBPI_BtlGuiContactor_C) == 0x000028, "Wrong size on IBPI_BtlGuiContactor_C");

}

