#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FBtlAlloutSequencer

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct FBtlAlloutSequencer.FBtlAlloutSequencer
// 0x0050 (0x0050 - 0x0000)
struct FFBtlAlloutSequencer final
{
public:
	TSoftObjectPtr<class ULevelSequence>          AlloutA_3_6BB02A2545F97D578EB628B91453C2D1;        // 0x0000(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TSoftObjectPtr<class ULevelSequence>          AlloutB_5_02F9C02B49E5BE673FE8958AEADEA3FA;        // 0x0028(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
};
static_assert(alignof(FFBtlAlloutSequencer) == 0x000008, "Wrong alignment on FFBtlAlloutSequencer");
static_assert(sizeof(FFBtlAlloutSequencer) == 0x000050, "Wrong size on FFBtlAlloutSequencer");
static_assert(offsetof(FFBtlAlloutSequencer, AlloutA_3_6BB02A2545F97D578EB628B91453C2D1) == 0x000000, "Member 'FFBtlAlloutSequencer::AlloutA_3_6BB02A2545F97D578EB628B91453C2D1' has a wrong offset!");
static_assert(offsetof(FFBtlAlloutSequencer, AlloutB_5_02F9C02B49E5BE673FE8958AEADEA3FA) == 0x000028, "Member 'FFBtlAlloutSequencer::AlloutB_5_02F9C02B49E5BE673FE8958AEADEA3FA' has a wrong offset!");

}

