#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LV_F001_001_UI

#include "Basic.hpp"


namespace SDK::Params
{

// Function LV_F001_001_UI.LV_F001_001_UI_C.ExecuteUbergraph_LV_F001_001_UI
// 0x0004 (0x0004 - 0x0000)
struct LV_F001_001_UI_C_ExecuteUbergraph_LV_F001_001_UI final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LV_F001_001_UI_C_ExecuteUbergraph_LV_F001_001_UI) == 0x000004, "Wrong alignment on LV_F001_001_UI_C_ExecuteUbergraph_LV_F001_001_UI");
static_assert(sizeof(LV_F001_001_UI_C_ExecuteUbergraph_LV_F001_001_UI) == 0x000004, "Wrong size on LV_F001_001_UI_C_ExecuteUbergraph_LV_F001_001_UI");
static_assert(offsetof(LV_F001_001_UI_C_ExecuteUbergraph_LV_F001_001_UI, EntryPoint) == 0x000000, "Member 'LV_F001_001_UI_C_ExecuteUbergraph_LV_F001_001_UI::EntryPoint' has a wrong offset!");

}

