#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LV_Xrd777_P

#include "Basic.hpp"

#include "LV_Xrd777_P_classes.hpp"
#include "LV_Xrd777_P_parameters.hpp"


namespace SDK
{

// Function LV_Xrd777_P.LV_Xrd777_P_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ALV_Xrd777_P_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LV_Xrd777_P_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LV_Xrd777_P.LV_Xrd777_P_C.ExecuteUbergraph_LV_Xrd777_P
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALV_Xrd777_P_C::ExecuteUbergraph_LV_Xrd777_P(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LV_Xrd777_P_C", "ExecuteUbergraph_LV_Xrd777_P");

	Params::LV_Xrd777_P_C_ExecuteUbergraph_LV_Xrd777_P Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

