#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MantleType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum MantleType.MantleType
// NumValues: 0x0004
enum class EMantleType : uint8
{
	NewEnumerator1                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator2                           = 2,
	MantleType_MAX                           = 3,
};

}

